### ISSUE TITLE
Indisposibilité de télécharger les fichiers pour une commune (Charny Orée de Puisaye COG=89086)

### ISSUE THREAD

**Issue by jerbou** [etalab/cadastre.data.gouv.fr#109]
Bonjour,

Une remontée utilisateur qui ne peux pas télécharger le cadastre de la commune de Charny Orée de Puisaye (COG=89086).
Serait il possible de regarder cela ?

C'est une commune fusionnée :
https://www.insee.fr/fr/metadonnees/cog/commune/COM89086-charny-oree-de-puisaye

![image](https://user-images.githubusercontent.com/7600693/138446741-36ad844a-3523-44ec-ac88-b2f9fb435e8b.png)

D'avance Merci,

Jérôme Boutet
IDéO BFC

**Comment by jerbou** [comment]
Les utilisateurs nous relancent sur le besoin. Avez eu des nouvelles par rapport à vos interlocuteurs DGFIP ?

D'avance Merci,
Jérôme Boutet

**Comment by ThomasG77** [comment]
@jerbou En attente, on les a relancé à nouveau. Je mettrais à jour l'issue dès que j'ai plus d'infos.

**Comment by jerbou** [comment]
Merci pour la relance, j'en ai informé les utilisateurs.

**Comment by ThomasG77** [comment]
Bonjour,

Je reviens enfin vers vous. Les données d'octobre 2021 ont été publiées. La commune manquante 89086 est bien présente dans la livraison. Je ferme mais n'hésitez pas à commenter ou à ouvrir une autre issue si vous avez d'autres problèmes.

**Comment by jerbou** [comment]
Merci @ThomasG77 , je passe le relai aux utilisateurs.
Je constate que le téléchargement est possible sur notre carte / relai 
https://cartes.ternum-bfc.fr/?config=apps/gip-territoires-numeriques-bfc/cadastre.xml#
