### ISSUE TITLE
Cadastre - Script vérification du contenu des livraisons DGFIP amont

### ISSUE THREAD

**Issue by ThomasG77** [etalab/cadastre.data.gouv.fr#112]
Lié à #109

**Comment by geoffreyaldebert** [comment]
Stratégie : 
- Lister l'ensemble des fichiers en erreur sur les 3 derniers millésimes. 
- Envoyer cette liste à la DGFIP pour demande d'explication et investigation

**Comment by ThomasG77** [comment]
Exemple https://github.com/etalab/cadastre/issues/71

**Comment by ThomasG77** [comment]
2 niveaux:
- amont (dès livraison)
- aval (après traitement)
