### ISSUE TITLE
Hébergez-vous plusieurs versions de la carte des cadastres ?

### ISSUE THREAD

**Issue by itytophile** [etalab/cadastre.data.gouv.fr#129]
Bonjour,

Je développe une application qui permet aux utilisateurs de sélectionner leurs bâtiments et leurs parcelles cadastrales via la carte que vous hébergez sur https://openmaptiles.geo.data.gouv.fr/data/cadastre.json

Récemment, il y a eu une mise à jour de la carte et les `id` des `Feature` ont changé.

Ma question est la suivante: l'ancienne version de la carte est-elle toujours hébergée ? Ou dois-je moi-même héberger l'ancienne version ?

Merci et bon courage.

**Comment by ThomasG77** [comment]
La majorité des `id` des features ne changent pas mais comme des parcelles sont créées ou disparaissent, certains `id` changent. Si vous voulez être synchronisé entre la carte et les données d'une même livraison, vous devrez vous même héberger car nous n'hébergeons que la version courante du cadastre.

Nous utilisons le package Node `tileserver-gl-light` pour servir les tuiles avec le package `pm2`. Nous utilisons également Nginx pour gérer le domaine.
L'URL des différentes tuiles est `https://cadastre.data.gouv.fr/data/etalab-cadastre/<millesime>/mbtiles/france/` ou `<millesime>` est `2022-04-01` ou `2022-07-01` comme par exemple https://cadastre.data.gouv.fr/data/etalab-cadastre/2022-04-01/mbtiles/france/

**Comment by itytophile** [comment]
Ok je vois, merci beaucoup !

Je verrai quelle décision prendre. Bon courage.
