### ISSUE TITLE
Ajouter le champs commune (code insee) dans la couche commune

### ISSUE THREAD

**Issue by yjacolin** [etalab/cadastre.data.gouv.fr#48]
La couche commune est la seule couche ne contenant pas de champ "commune" (ie le code insee). Par contre elle est la seule contenant le nom de la commune (champ "nom").

Est il possible d'améliorer la cohérence des données en rajoutant ce champs "commune" dans la couche "commune" ? Cela permet d'automatiser la récupération des couches et de filtrer les communes de manière identique pour toutes les couches que vous fournissez. Merci.

**Comment by jdesboeufs** [comment]
Je ferme ici car j'ai créé l'issue au bon endroit.
https://github.com/etalab/cadastre/issues/45
