### ISSUE TITLE
Le lien en haut à gauche mène à une erreur 404

### ISSUE THREAD

**Issue by PoignardAzur** [etalab/cadastre.data.gouv.fr#69]
Dans n'importe quelle partie du site, cliquer sur l'icône en haut à gauche mène à la page `https://cadastre.data.gouv.fr/` sans recharger la page, ce qui est probablement le comportement attendu.

Cependant, si on essaie d'ouvrir ce lien dans un nouvel onglet, ou un autre méthode pour récupérer la "vraie" valeur du lien, il mène alors à la page `https://cadastre.data.gouv.fr/index.html`, qui n'existe pas, et affiche une erreur 404.

Problème bête mais simple à régler =)

(la page 404 elle même mériterait un peu plus d'attention)

**Comment by jdesboeufs** [comment]
Merci pour votre retour très pertinent.
On va corriger certains de nos sites qui ont le même comportement.
