### ISSUE TITLE
Version de postgis

### ISSUE THREAD

**Issue by MathRobin** [etalab/cadastre.data.gouv.fr#84]
Hello !

Merci pour ce que vous faites pour l'open data, c'est trop cool !

Je sens que je ne pose pas la question au bon endroit mais je ne trouve pas l'info.

Si je veux insérer l'un des fichiers chargés dans postgis, quelle version utiliser ?

J'ai essayé avec postgis 3, ça marche pas, ça me dit qu'il y a une fonction `AddGeometryColumn` qui n'existe pas

```
 returned 0 [ERROR:  function addgeometrycolumn(text, unknown, unknown, integer, unknown, integer) does not exist
LIGNE 843 : SELECT AddGeometryColumn ( current_schema::text, 'geo_commun...
                   ^
ASTUCE : No function matches the given name and argument types. You might need to add explicit type casts.
]
```

Merci du coup de main par avance

**Comment by ThomasG77** [comment]
Sans rapport, je ferme.

Je pense que vous avez déjà trouvé sinon la solution était d'installer PostGIS puis dans votre base de lancer l'instruction "CREATE EXTENSION postgis;" Votre problème n'est pas liée à la version de PostGIS.

**Comment by MathRobin** [comment]
C'est ce que j'avais fait pourtant. Depuis j'ai eu quelques changements de priorités, je sais pas si j'aurai l'occasion de me repencher sur ce problème
