### ISSUE TITLE
coquille sur daterubrique hitorique

### ISSUE THREAD

**Issue by SOGEFI** [etalab/cadastre.data.gouv.fr#86]
https://cadastre.data.gouv.fr/datasets/cadastre-etalab

anglicisme sur la date à corriger

"02/13/2020 : nouveau millésime PCI + nouvelles données Strasbourg" > "13/02/2020 : nouveau millésime PCI + nouvelles données Strasbourg"

**Comment by ThomasG77** [comment]
Solved with https://github.com/etalab/cadastre.data.gouv.fr/commit/9d2a442c7a8667dff49f035884fdf3ed67a13842
