### ISSUE TITLE
Mise à jour Juillet 2020 et "bundler" choix de territoires ?

### ISSUE THREAD

**Issue by jerbou** [etalab/cadastre.data.gouv.fr#87]
Bonjour,

Pouvez confirmer que le "bundler" (choix territoires, par EPCI ou par commune) diffusent les données à jour du 1er Juillet 2020 ?
Aprés un test unitaire (en ayant télécharger le EDIGEO :
https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/2020-07-01/edigeo-cc/departements/
et en testant des changements sur deux trois commune, il semble que c'est effectivement le cas.

D'avance Merci,

Jérôme

**Comment by biratchet** [comment]
Bonjour,
D'ailleurs, puisque les données de ce bundler semblent à jour, d'où viennent-elles, SVP?
Désolé pour ce hors-sujet, mais on dénombre encore en 2020 de si nombreux ETP dans les services publics qui produisent et administrent leur "propre" référentiel administratif.
Bruno

**Comment by jdesboeufs** [comment]
Bonjour,

@jerbou Oui le bundler est bien branché sur les dernières données.
@biratchet Les données sont le mêmes que celles du répertoire public, mais dans certain cas regroupées à la volée, ou transcodés. Il s'agit en fait de ce code (peu documenté) : https://github.com/etalab/cadastre-bundler-api

**Comment by jdesboeufs** [comment]
Et je précise pour @biratchet que Etalab est en charge de la diffusion du plan cadastral.
Ces fichiers dans les formats GeoJSON et SHP ne sont pas différents, ils sont juste plus adaptés à certaines catégories d'utilisateurs.

**Comment by jerbou** [comment]
Merci beaucoup @jdesboeufs pour la réponse.

Nous avons fait une petite carte "facilitant" le téléchargement pour les com de BFC :
https://cartes.ternum-bfc.fr/?config=apps/gip-territoires-numeriques-bfc/cadastre.xml

Juste dernière question : le découpage EPCI est il toujours en prévision ou pas du tout ?
Promis, aprés, on peut clore ;)

Jérôme Boutet

**Comment by jerbou** [comment]
Je clos ;)
